mytestkey=This value is from LOCAL properties file

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:mysql://localhost:3306/payments
spring.datasource.username=payments
spring.datasource.password=P9v@tX3#nLz!Q8wK
	
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

stripe.provider.service.url=http://localhost:8083/v1/session
stripe.provider.service.session.create.path=/create
stripe.provider.service.session.retrieve.path=/retrieve
stripe.provider.service.session.expire.path=/expire
