spring.config.import=optional:file:.env[.properties]

stripe.session.create.url=https://api.stripe.com/v1/checkout/sessions
stripe.session.retrieve.url=https://api.stripe.com/v1/checkout/sessions/{id}
stripe.session.expire.url=https://api.stripe.com/v1/checkout/sessions/{id}/expire

stripe.processing.service.url=http://localhost
stripe.processing.service.port=8082
stripe.processing.service.path=/v1/payments
stripe.processing.service.success=/success
stripe.processing.service.failed=/failed