package com.hulkhiretech.payments.controller.pojo;

import java.util.List;

import lombok.Data;

@Data
public class SessionCreateRequest
{
	/**
	 * Client reference ID for tracking, generated by processing service
	 */
	private String clientReferenceId;
	
	private String currency;
	private String successUrl;
	private String cancelUrl;
	private List<String> paymentMethods;
	
	private List<Product> products;
	
	@Data
	public static class Product
	{
		private String productName;
		private Long unitAmount; // cents
		private Long quantity;
	}
}
